node robotAvecCheerio.js %1 ;
phantomjs enleveCSS.js "http://localhost/projetoption/" "a" ;
phantomjs enleveJS.js "http://localhost/projetoption/" "b" ;
phantomjs enleveJS.js "http://localhost/projetoption/" "a" ;
phantomjs skynet.js "http://localhost/projetoption/b/b.html" ;
node scripts.js %1 ;
phantomjs robot.js "http://localhost/projetoption/a/a.html" "1" ;
phantomjs robot.js "http://localhost/projetoption/b/b.html" "2" ;
phantomjs robot.js %1 "3" ;
node difference.js ;